version: '3.4'
services:

    postgres:
        image: fetchq/fetchq:10.4-1.3.0
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${PG_USERNAME:-berlin}
            POSTGRES_PASSWORD: ${PG_PASSWORD:-berlin}
            POSTGRES_DB: ${PG_DATABASE:-berlin}
        volumes:
            - ${HUMBLE_DATA:-./data}/pg:/var/lib/postgresql/data
            - ${HUMBLE_BACKUP:-./data/backup}/pg:/backup
        restart: always
